version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # バインド: ホストのファイルをコンテナの指定ディレクトリにコピー
      # ホストディレクトリ:コンテナのルート Dockerfileで指定
      - ./app:/usr/src/app  
      # ボリューム: コンテナに依存しないボリューム領域を作成しデータを永続化することも可能
    command: sh -c "npm i && npm run dev"
    env_file:
      - .env
    ports:
      - "3000:3000"